import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { signIn, signOut, useSession } from 'next-auth/react'
import { useCallback, useState } from 'react'
import ReactTags, { Tag } from 'react-tag-autocomplete'
import debounce from 'lodash/debounce';
import { FaXbox, FaPlaystation, FaRegSave, FaDiscord } from 'react-icons/fa';
import { BsNintendoSwitch } from 'react-icons/bs';
import { GiComputerFan } from 'react-icons/gi';
import { MdLogout } from 'react-icons/md';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession()
  const [games, setGames] = useState<Tag[]>([])
  const [isBusy, setIsBusy] = useState(false)
  const [suggestions, setSuggestions] = useState<Tag[]>([])

  const onDelete = useCallback((gameIndex: number) => {
    setGames(games.filter((_, i) => i !== gameIndex))
  }, [games])

  const onAddition = useCallback((newGame: Tag) => {
    setGames([...games, newGame])
  }, [games])

  const onInput = (query: string) => {
    if (!isBusy && query.length >= 2) {
      setIsBusy(true)

      return fetch(`/api/games?searchTerm=${query}`)
        .then((response) => response.json())
        .then((data: Tag[]) => {
          setIsBusy(false)
          console.log('data', data)
          if (data instanceof Array) {
            setSuggestions(data)
          }
        })
    }
  }

  const debouncedOnInput = useCallback(debounce(onInput, 700), [games])

  return (
    <>
      <Head>
        <title>Gaming Planner</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ height: '100vh', padding: 8 }}>
        <div style={{ display: 'flex', justifyContent: 'flex-end', padding: 8 }}>
          {!!session?.user && <p style={{ display: 'flex', alignItems: 'center' }}>
            {!!session?.user?.image && <Image
              src={session?.user?.image}
              alt="User Avatar"
              width={24}
              height={24}
              priority
              style={{ borderRadius: '50%' }}
            />}
            <span style={{ marginLeft: 8, marginRight: 8 }}>{session?.user?.name}</span>
            <MdLogout onClick={() => signOut()}/>
          </p>}
        </div>
        {session ? <>
          <div style={{ display: 'inline-flex', flexWrap: 'wrap', alignItems: 'center', flexDirection: 'row', gap: 12, marginBottom: 8 }}>
            Wybierz platformy:
            <button style={{ padding: 4, display: 'flex', alignItems: 'center' }}><GiComputerFan />&nbsp;PC</button>
            <button style={{ padding: 4, display: 'flex', alignItems: 'center' }}><FaXbox />&nbsp;Xbox</button>
            <button style={{ padding: 4, display: 'flex', alignItems: 'center' }}><FaPlaystation />&nbsp;PS</button>
            <button style={{ padding: 4, display: 'flex', alignItems: 'center' }}><BsNintendoSwitch />&nbsp;Switch</button>
          </div>
          <span>
            <ReactTags
              tags={games}
              maxSuggestionsLength={15}
              suggestions={suggestions}
              onDelete={onDelete}
              onAddition={onAddition}
              allowBackspace={false}
              suggestionsFilter={() => true}
              onInput={debouncedOnInput}
              placeholderText="Wpisz nazwę gry, która cię interesuje"
            />
            {isBusy && <p>Wczytywanie...</p>}
          </span>
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: 8 }}>
            <button style={{ padding: 4, display: 'flex', alignItems: 'center' }}><FaRegSave />&nbsp;Zapisz</button>
          </div>
        </>
          :
          <div>
            <div style={{ display: 'flex', justifyContent: 'center', marginTop: 8 }}>
              <button style={{ padding: 4, display: 'flex', alignItems: 'center' }} onClick={() => signIn('discord')}><FaDiscord/>&nbsp;Zaloguj się</button>
            </div>
          </div>}
      </main>
    </>
  )
}
